version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    userns_mode: auto
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: SSL://localhost:29092
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-server.p12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: creds_server
      KAFKA_SSL_KEY_CREDENTIALS: creds_server
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_TRUSTSTORE_FILENAME: ca.p12
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds_ca
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SUPER_USERS: 'User:CN=server'
    volumes:
      - ./certCreation/secrets/server:/etc/kafka/secrets

  producer:
    build:
      context: .
      dockerfile: Producer/Dockerfile
    userns_mode: auto
    volumes:
      - ./certCreation/secrets/client:/certs
    depends_on:
      - kafka
